import type { ConversationEvent } from './types';

function hoursAgo(hours: number): string {
  return new Date(Date.now() - hours * 60 * 60 * 1000).toISOString();
}

export function demoConversations(): ConversationEvent[] {
  return [
    {
      id: 'demo-01',
      occurredAt: hoursAgo(1),
      sessionId: 'sess-ana',
      visitante: 'Ana',
      pergunta: 'Quais projetos você tem no portfólio?',
      resposta:
        'Tenho quatro projetos no ar. O VendaCore ERP, um ERP modular em .NET 8 e React, demo em https://reat-erp.vercel.app/. O Smarty Hardware, e-commerce de peças de PC. O Kanban Board MVP para times ágeis. E o Chat Observability, o painel Grafana das conversas deste chat. Todos têm demo na Vercel.',
      latenciaMs: 1840,
      modelo: 'command-a-03-2025',
      origemHash: 'a1b2c3d4e5f6a7b8',
      erro: null,
      source: 'chatbot',
    },
    {
      id: 'demo-02',
      occurredAt: hoursAgo(3),
      sessionId: 'sess-carlos',
      visitante: 'Carlos',
      pergunta: 'Qual a stack do Kanban?',
      resposta:
        'O Kanban usa NestJS, Prisma, PostgreSQL e Socket.IO no back, e Next.js 14 com Tailwind no front.',
      latenciaMs: 1320,
      modelo: 'command-a-03-2025',
      origemHash: 'b2c3d4e5f6a7b8c9',
      erro: null,
      source: 'chatbot',
    },
    {
      id: 'demo-03',
      occurredAt: hoursAgo(5),
      sessionId: 'sess-anon-1',
      visitante: null,
      pergunta: 'Como posso entrar em contato?',
      resposta: 'Pode me chamar no LinkedIn ou pelo e-mail joshuaatsilva@gmail.com.',
      latenciaMs: 980,
      modelo: 'command-a-03-2025',
      origemHash: 'c3d4e5f6a7b8c9d0',
      erro: null,
      source: 'chatbot',
    },
    {
      id: 'demo-04',
      occurredAt: hoursAgo(8),
      sessionId: 'sess-luiza',
      visitante: 'Luiza',
      pergunta: 'Você trabalha com ERP?',
      resposta:
        'Sim. No trabalho atuo em ERP com Laravel e, no portfólio, o VendaCore ERP mostra o mesmo domínio em .NET 8 com CQRS e React. Demo: https://reat-erp.vercel.app/',
      latenciaMs: 1560,
      modelo: 'command-a-03-2025',
      origemHash: 'd4e5f6a7b8c9d0e1',
      erro: null,
      source: 'chatbot',
    },
    {
      id: 'demo-05',
      occurredAt: hoursAgo(22),
      sessionId: 'sess-pedro',
      visitante: 'Pedro',
      pergunta: 'O Smarty Hardware tem checkout?',
      resposta:
        'Tem. O checkout busca CEP no ViaCEP, aceita pagamentos fictícios e tem painel admin para venda no balcão.',
      latenciaMs: 2010,
      modelo: 'command-a-03-2025',
      origemHash: 'e5f6a7b8c9d0e1f2',
      erro: null,
      source: 'chatbot',
    },
    {
      id: 'demo-06',
      occurredAt: hoursAgo(26),
      sessionId: 'sess-ana',
      visitante: 'Ana',
      pergunta: 'A Mia do Smarty é um chatbot?',
      resposta: 'É a assistente virtual da loja, pensada para tirar dúvidas do catálogo e do atendimento.',
      latenciaMs: 1105,
      modelo: 'command-a-03-2025',
      origemHash: 'a1b2c3d4e5f6a7b8',
      erro: null,
      source: 'chatbot',
    },
    {
      id: 'demo-07',
      occurredAt: hoursAgo(30),
      sessionId: 'sess-fail',
      visitante: 'Marina',
      pergunta: 'Me fala da sua experiência com NestJS',
      resposta: '',
      latenciaMs: 30120,
      modelo: 'command-a-03-2025',
      origemHash: 'f6a7b8c9d0e1f2a3',
      erro: 'Cohere timeout',
      source: 'chatbot',
    },
    {
      id: 'demo-08',
      occurredAt: hoursAgo(40),
      sessionId: 'sess-joao',
      visitante: 'João',
      pergunta: 'Onde você mora?',
      resposta: 'Moro em Curitiba, Paraná.',
      latenciaMs: 760,
      modelo: 'command-a-03-2025',
      origemHash: 'aabbccddeeff0011',
      erro: null,
      source: 'chatbot',
    },
    {
      id: 'demo-09',
      occurredAt: hoursAgo(50),
      sessionId: 'sess-carla',
      visitante: 'Carla',
      pergunta: 'Você usa agentes de IA no dia a dia?',
      resposta:
        'Sim. Tenho forte interesse em agentes inteligentes para acelerar entregas e automatizar processos.',
      latenciaMs: 1444,
      modelo: 'command-a-03-2025',
      origemHash: '1122334455667788',
      erro: null,
      source: 'chatbot',
    },
    {
      id: 'demo-10',
      occurredAt: hoursAgo(55),
      sessionId: 'sess-anon-2',
      visitante: null,
      pergunta: 'oi',
      resposta: 'Oi! Antes de continuar, como posso te chamar?',
      latenciaMs: 120,
      modelo: null,
      origemHash: '99aa88bb77cc66dd',
      erro: null,
      source: 'chatbot',
    },
    {
      id: 'demo-11',
      occurredAt: hoursAgo(70),
      sessionId: 'sess-rafa',
      visitante: 'Rafael',
      pergunta: 'O Kanban tem apontamento de horas?',
      resposta: 'Tem Play/Pause e lançamento manual de horas em cada card, com sprint e tags.',
      latenciaMs: 1670,
      modelo: 'command-a-03-2025',
      origemHash: '2233445566778899',
      erro: null,
      source: 'chatbot',
    },
    {
      id: 'demo-12',
      occurredAt: hoursAgo(90),
      sessionId: 'sess-bia',
      visitante: 'Bia',
      pergunta: 'Qual sua formação?',
      resposta: 'Sou formado em Tecnologia da Informação pela PUC-PR e também cursei História na UNINTER.',
      latenciaMs: 1255,
      modelo: 'command-a-03-2025',
      origemHash: '3344556677889900',
      erro: null,
      source: 'chatbot',
    },
    {
      id: 'demo-13',
      occurredAt: hoursAgo(110),
      sessionId: 'sess-carlos',
      visitante: 'Carlos',
      pergunta: 'Os projetos têm testes?',
      resposta: 'Sim. O Kanban tem Jest, Supertest e Cypress. O Smarty tem PHPUnit e Cypress. O VendaCore tem testes de unidade, integração e de arquitetura no .NET.',
      latenciaMs: 1390,
      modelo: 'command-a-03-2025',
      origemHash: 'b2c3d4e5f6a7b8c9',
      erro: null,
      source: 'chatbot',
    },
    {
      id: 'demo-14',
      occurredAt: hoursAgo(140),
      sessionId: 'sess-ana',
      visitante: 'Ana',
      pergunta: 'Posso ver o código no GitHub?',
      resposta: 'Sim, meu GitHub é github.com/exkgred.',
      latenciaMs: 890,
      modelo: 'command-a-03-2025',
      origemHash: 'a1b2c3d4e5f6a7b8',
      erro: null,
      source: 'chatbot',
    },
    {
      id: 'demo-15',
      occurredAt: hoursAgo(180),
      sessionId: 'sess-paulo',
      visitante: 'Paulo',
      pergunta: 'Você atua com Laravel?',
      resposta: 'Atuo. O Smarty Hardware, por exemplo, é Laravel 11 com use cases e repositórios.',
      latenciaMs: 1180,
      modelo: 'command-a-03-2025',
      origemHash: '445566778899aabb',
      erro: null,
      source: 'chatbot',
    },
    {
      id: 'demo-16',
      occurredAt: hoursAgo(210),
      sessionId: 'sess-anon-3',
      visitante: null,
      pergunta: 'O que é o Chat Observability / Grafana?',
      resposta:
        'É o painel das conversas deste chatbot. O chat responde na hora e o log segue depois para o dashboard e para o Grafana Cloud Loki. Demo: https://chat-observability.vercel.app/',
      latenciaMs: 1520,
      modelo: 'command-a-03-2025',
      origemHash: '5566778899aabbcc',
      erro: null,
      source: 'chatbot',
    },
    {
      id: 'demo-17',
      occurredAt: hoursAgo(250),
      sessionId: 'sess-fernanda',
      visitante: 'Fernanda',
      pergunta: 'O Kanban atualiza em tempo real?',
      resposta: 'Sim, via WebSocket. Quando alguém move um card, o quadro dos outros atualiza na hora.',
      latenciaMs: 1410,
      modelo: 'command-a-03-2025',
      origemHash: '66778899aabbccdd',
      erro: null,
      source: 'chatbot',
    },
    {
      id: 'demo-18',
      occurredAt: hoursAgo(280),
      sessionId: 'sess-error-2',
      visitante: 'Diego',
      pergunta: 'Quais bancos você usa?',
      resposta: '',
      latenciaMs: null,
      modelo: 'command-a-03-2025',
      origemHash: '778899aabbccddee',
      erro: 'COHERE_API_KEY ausente',
      source: 'chatbot',
    },
    {
      id: 'demo-19',
      occurredAt: hoursAgo(300),
      sessionId: 'sess-sofia',
      visitante: 'Sofia',
      pergunta: 'Você faz frontend também?',
      resposta: 'Faço. Vue 3 e Next.js/React, com Tailwind, Pinia e Zustand conforme o projeto.',
      latenciaMs: 1275,
      modelo: 'command-a-03-2025',
      origemHash: '8899aabbccddeeff',
      erro: null,
      source: 'chatbot',
    },
    {
      id: 'demo-20',
      occurredAt: hoursAgo(330),
      sessionId: 'sess-luiza',
      visitante: 'Luiza',
      pergunta: 'Tem vaga para conversarmos sobre uma oportunidade?',
      resposta: 'Claro. Me chama no LinkedIn ou no e-mail que a gente agenda.',
      latenciaMs: 990,
      modelo: 'command-a-03-2025',
      origemHash: 'd4e5f6a7b8c9d0e1',
      erro: null,
      source: 'chatbot',
    },
    {
      id: 'demo-21',
      occurredAt: hoursAgo(12),
      sessionId: 'sess-carla',
      visitante: 'Carla',
      pergunta: 'Como o VendaCore ERP foi construído?',
      resposta:
        'Clean Architecture com CQRS no .NET 8: a API dispara commands MediatR, o domínio guarda as regras (pedido, estoque, dinheiro) e o EF Core fica na infrastructure. O React na Vercel é estático, com VITE_DEMO, sem a API. Demo: https://reat-erp.vercel.app/',
      latenciaMs: 1680,
      modelo: 'command-a-03-2025',
      origemHash: '3344556677889900',
      erro: null,
      source: 'chatbot',
    },
  ];
}
